baseurl            = "https://casvancooten.com"
title              = "Cas' Security Ramblings"
languageCode       = "en-us"
theme              = "hello-friend-ng"

enableEmoji        = true
enableGitInfo      = true

PygmentsCodeFences = true
PygmentsStyle      = "native"

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006"
  
  homeSubtitle = "I ramble about security stuff, mostly"

  disableReadOtherPosts = false

  description = "A blog about security stuff, mostly"
  keywords = "homepage, blog, cas van cooten, security, hacking"

  images = ["/preview.png"]
  contentTypeName = "posts"
  enableThemeToggle = true
  defaultTheme = "dark"

  [params.logo]
    logoText = "Security Ramblings"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/chvancooten"

  [[params.social]]
    name = "email"
    url  = "mailto:hello@casvancooten.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/chvancooten"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/chvancooten/"

  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "<a href=\"http://gohugo.io\">Hugo</a> theme by <a href=\"https://github.com/rhazdon\">rhazdon</a>"
    ]

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"
